Update .pre-commit-config.yaml

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -18,11 +18,40 @@ repos:
         pass_filenames: false
         stages: [commit]
         
+repos:
+-   repo: https://github.com/pre-commit/pre-commit-hooks
+    rev: v3.2.0
+    hooks:
+    -   id: check-yaml
+    -   id: trailing-whitespace
+    -   id: end-of-file-fixer
+-   repo: https://github.com/psf/black
+    rev: 19.3b0
+    hooks:
+    -   id: black
+-   repo: local
+    hooks:
+    -   id: check-date-format
+        name: Check if the date in the qmd file is in proper format
+        entry: sh checkDate.sh
+        language: system
+        pass_filenames: false
+        stages: [commit]
+
 # Run command to exclude files from git index if modified outside allowed folders
 -   repo: local
     hooks:
     -   id: exclude-files-from-commit
         name: Exclude files from commit
-        entry: sh excludeFiles.sh
+        entry: |
+          #!/bin/bash
+          
+          # Find modified files that are not in the allowed folders
+          modified_files=$(git status --porcelain | awk '{print $2}' | grep -vE "^about/|^posts/|^_freeze/")
+
+          if [ ! -z "$modified_files" ]; then
+            echo "Cannot commit files outside of 'about/', 'posts/', and '_freeze/' folders. Please move the modified files into one of these folders before committing."
+            exit 1
+          fi
         language: system
         stages: [commit]
